/**
 * Browser Automation Module for O.G.R.E Grading Server
 *
 * Simplified for extension-based grading.
 * Extension handles all DOM extraction and filling using chrome.scripting APIs.
 * This module only manages session tokens for authentication.
 */

// ============================================================================
// Session Store
// ============================================================================

/** @type {Map<string, SessionGrant>} */
const activeSessions = new Map();

/**
 * @typedef {Object} SessionGrant
 * @property {string} sessionToken - UUID generated by extension
 * @property {number} tabId - Chrome tab ID (for reference)
 * @property {string} url - Exact URL pattern allowed
 * @property {string} grantedBy - Extension ID that granted access
 * @property {Date} grantedAt - When the session was granted
 * @property {Date} expiresAt - When the session expires (1 hour default)
 * @property {string} scope - Permission scope (always 'automation' for now)
 */

// ============================================================================
// Session Management
// ============================================================================

/**
 * Grant a new automation session
 * @param {string} sessionToken - UUID generated by extension
 * @param {number} tabId - Chrome tab ID
 * @param {string} url - Page URL
 * @param {string} grantedBy - Extension ID
 * @param {Date} expiresAt - Expiration timestamp
 * @returns {SessionGrant}
 */
export function grantSession(sessionToken, tabId, url, grantedBy, expiresAt) {
  const session = {
    sessionToken,
    tabId,
    url,
    grantedBy,
    grantedAt: new Date(),
    expiresAt: new Date(expiresAt),
    scope: 'automation'
  };

  activeSessions.set(sessionToken, session);
  console.log(`[Automation] Session granted: ${sessionToken} (expires: ${session.expiresAt.toISOString()})`);

  return session;
}

/**
 * Validate a session token
 * @param {string} sessionToken
 * @returns {SessionGrant}
 * @throws {Error} if session is invalid or expired
 */
export function validateSession(sessionToken) {
  const session = activeSessions.get(sessionToken);

  if (!session) {
    throw new Error('Invalid session token');
  }

  if (Date.now() > session.expiresAt.getTime()) {
    activeSessions.delete(sessionToken);
    throw new Error('Session expired');
  }

  return session;
}

/**
 * Revoke a session
 * @param {string} sessionToken
 */
export function revokeSession(sessionToken) {
  const deleted = activeSessions.delete(sessionToken);
  if (deleted) {
    console.log(`[Automation] Session revoked: ${sessionToken}`);
  }
  return deleted;
}

/**
 * Clean up expired sessions (run periodically)
 */
export function cleanupExpiredSessions() {
  const now = Date.now();
  let cleaned = 0;

  for (const [token, session] of activeSessions.entries()) {
    if (now > session.expiresAt.getTime()) {
      activeSessions.delete(token);
      cleaned++;
    }
  }

  if (cleaned > 0) {
    console.log(`[Automation] Cleaned up ${cleaned} expired session(s)`);
  }
}

// Run cleanup every 5 minutes
setInterval(cleanupExpiredSessions, 5 * 60 * 1000);
